#!/usr/bin/env python3
# ==============================================================
# build_pardalote.py
# Concatenate the modular Pardalote JS sources (lib/src/) into the
# single distribution bundle lib/pardalote.js.
#
# Why a bundle: the p5.js Web Editor preprocesses each *separate*
# local .js file through esprima/escodegen and chokes on the
# extension files as standalone programs. Concatenated into one
# file they ride along untouched. The bundle is the file students
# include; the modular sources in lib/src/ stay the source of truth.
#
# Order matters: the core defines Extension / Arduino /
# registerExtensionType / encodeFrame, which every extension
# references, so it goes first. Extensions have no inter-deps.
#
# Board pin maps (lib/pardalote-pins-*.js) are per-board and mutually
# exclusive, so they are NOT bundled — include one by hand.
#
# Usage:  python3 build_pardalote.py
# ==============================================================
import json
from pathlib import Path

REPO = Path(__file__).parent
SRC  = REPO / "lib" / "src"
OUT  = REPO / "lib" / "pardalote.js"
VERSION = json.loads((REPO / "lib" / "package.json").read_text(encoding="utf-8"))["version"]

# Core first, then extensions (any order — no inter-dependencies).
FILES = [
    "pardalote-core.js",
    "pardalote-servo.js",
    "pardalote-bus-servo.js",
    "pardalote-stepper.js",
    "pardalote-neopixel.js",
    "pardalote-ultrasonic.js",
    "pardalote-imu.js",
    "pardalote-encoder.js",
    "pardalote-camera.js",
]

BANNER = (
    "// ==============================================================\n"
    f"// pardalote.js {VERSION} — DISTRIBUTION BUNDLE. DO NOT EDIT.\n"
    "// https://github.com/ScottMit/Pardalote\n"
    "// Copyright (C) 2026 Scott Mitchell — GPL-3.0-or-later. See LICENSE.\n"
    "//\n"
    "// Generated by build_pardalote.py from the modular sources in\n"
    "// lib/src/ (core + extensions). Edit those and rebuild.\n"
    "// Board pin maps (pardalote-pins-*.js) are NOT bundled — add one\n"
    "// by hand for your board.\n"
    "// ==============================================================\n\n"
)


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    parts = [BANNER]
    for name in FILES:
        path = SRC / name
        if not path.exists():
            raise SystemExit(f"missing source: {path}")
        parts.append(
            f"// ----- {name} "
            + "-" * max(0, 54 - len(name))
            + "\n"
        )
        parts.append(path.read_text(encoding="utf-8").rstrip() + "\n\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(REPO)}  ({len(FILES)} sources, {kb:.1f} KB)")


if __name__ == "__main__":
    main()
